### ISSUE TITLE
On dynamic imports, registry

### ISSUE THREAD

**Issue by gzuidhof** [manzt/numcodecs.js#2]
I am a big proponent of supporting some sort of dynamic registry or dynamic loading, but I think there is a better approach than using the window/global object. I think the best we can do is making sure Zarr and numcodecs are tree shakable (they are so far). 

Loading codecs however is however inherently dynamic, at compile time you don't know which codecs will be used in your app using zarr.

I think numcodecs shouldn't contain the registry. Having implementations in separate files, that can be individually imported (like it is already, which is great!), is the most portable solution and keeps things simple. I think it should live either in Zarr itself, or in the user application using zarr or numcodecs directly.

One reason why I think it is difficult for for the registry to live there is because you don't know where the 'chunks' you dynamically load will live, right now in your code you talk to unpkg, but at least I personally like to self-host all dependencies (I don't want my app to break when unpkg goes down, however unlikely). 

Rollup has support for dynamic imports ([example repl](https://rollupjs.org/repl/?version=2.7.6&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMiUyRiolMjBEWU5BTUlDJTIwSU1QT1JUUyU1Q24lMjAlMjAlMjBSb2xsdXAlMjBzdXBwb3J0cyUyMGF1dG9tYXRpYyUyMGNodW5raW5nJTIwYW5kJTIwbGF6eS1sb2FkaW5nJTVDbiUyMCUyMCUyMHZpYSUyMGR5bmFtaWMlMjBpbXBvcnRzJTIwdXRpbGl6aW5nJTIwdGhlJTIwaW1wb3J0JTIwbWVjaGFuaXNtJTVDbiUyMCUyMCUyMG9mJTIwdGhlJTIwaG9zdCUyMHN5c3RlbS4lMjAqJTJGJTVDbmlmJTIwKGRpc3BsYXlNYXRoKSUyMCU3QiU1Q24lNUN0aW1wb3J0KCcuJTJGbWF0aHMuanMnKS50aGVuKGZ1bmN0aW9uJTIwKG1hdGhzKSUyMCU3QiU1Q24lNUN0JTVDdGNvbnNvbGUubG9nKG1hdGhzLnNxdWFyZSg1KSklM0IlNUNuJTVDdCU1Q3Rjb25zb2xlLmxvZyhtYXRocy5jdWJlKDUpKSUzQiU1Q24lNUN0JTdEKSUzQiU1Q24lN0QlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjBzcXVhcmUlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjAlN0JkZWZhdWx0JTIwYXMlMjBzcXVhcmUlN0QlMjBmcm9tJTIwJy4lMkZzcXVhcmUuanMnJTNCJTVDbiU1Q25leHBvcnQlMjBmdW5jdGlvbiUyMGN1YmUlMjAoeCUyMCklMjAlN0IlNUNuJTVDdHJldHVybiUyMHNxdWFyZSh4KSUyMColMjB4JTNCJTVDbiU3RCUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJzcXVhcmUuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwc3F1YXJlJTIwKCUyMHglMjApJTIwJTdCJTVDbiU1Q3RyZXR1cm4lMjB4JTIwKiUyMHglM0IlNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzbSUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0ElMjIwMCUyMiU3RA==)) , so does [Webpack](https://webpack.js.org/guides/code-splitting/#dynamic-imports) ([lazy loading](https://webpack.js.org/guides/lazy-loading/) docs). The real issue here is however that this outputs multiple JS files which can be dynamically imported, but that doesn't work if you have zarr as a dependency in your project. Monaco code editor uses dynamic imports (as it's huge, megabytes) and can be used as a dependency, but in order to do that they shipped their own webpack plugin which makes that possible..

I think for now the easiest thing is not to optimize for this and for V1 just import everything directly in Zarr. Two ideas for V2 with dynamic loading:

* A: **[This looks promising](https://webpack.js.org/api/module-methods/#magic-comments)**, maybe we can use `weak` dynamic imports in Zarr for large decompressors and use webpack generated code as our registry? This would be pretty great:

Failing example:
```
import {openArray} from `zarr`
const x = await openArray("my-blosc-array.zarr")
// Throws: no package `blosc` found, you can import it from `numcodecs`.
```

```
import("numcodecs/blosc`)
import {openArray} from `zarr`
const x = await openArray("my-blosc-array.zarr")
// No error as it was imported before (either dynamically or statically).
```
In this case the user can decide how to import these codecs with zarr, whether to lazy load them or just load them statically, and which ones :). Not sure this is possible though, and I actually suspect this lazy loading involves putting those libraries on the window object after all.

* B: We put a registry in zarr in a global variable, and allow the user to pass in additional compressors beyond the small built-in ones (gzip, zlib). Something like
```javascript
import {registerCompressor } from 'zarr'
import {myLargeCompressor} from 'numcodecs/my-large-compressor'
registerCompressor(myLargeCompressor)
// Or dynamically of course with await import
```

And we can perhaps ship two versions of zarr, one with all compressors built in, and one that requires dynamic loading.

**Comment by kylebarron** [comment]
(Disclaimer: I haven't read this whole thread yet.)

In [loaders.gl](https://loaders.gl) we do [dynamic library loading](https://loaders.gl/docs/whats-new#v20) for some file formats, specifically for code that runs on a web worker and/or requires large dependencies. So for example we load [this 1.6MB script](https://unpkg.com/@loaders.gl/draco@2.2.8/dist/draco-loader.worker.js) for parsing DRACO files dynamically from unpkg (hosted on NPM). This is helpful when you have an application where the user might have data in any arbitrary file format, and you don't want to pay the bundle size for formats the user won't end up using.

In terms of bundling, we just have scripts that create these web workers, and then we publish them as part of the bundle (but as separate files) to NPM on each release.

**Comment by manzt** [comment]
The thread is long, so I don't blame you 😄. Thanks for sharing what has worked for you in `loaders.gl`. I'm certainly interested in a robust way dynamically load codecs in applications using `zarr.js`.

> Since Blosc is only ~150kb(?) I'm not sure whether it's large enough to warrant the trouble of dynamic loading.

Currently my thinking is that we don't have enough codecs to warrant a sophisticated dynamic registry. Blosc is the default codec in `zarr-python`, and since we use `zarr.js` to view datasets that are on the order of 10s of GBs, the ergonomics bundling all the codecs (which usually together amount to less than singe data-chunk from a zarr-array) is worth it for the simplicity.

With that said, I'm open to thinking about solutions for dynamic imports in the future. Ideally, I'd like to decouple a codec registry from `zarr.js` completely, for multiple reasons:

1.) You don't pay for what you don't use.
2.) Users can swap in and out different codec implementations without changing `zarr.js` source. 
3.) A custom registry allows application-specific decisions over where decoding occurs (e.g. in a web worker).

The issue with pulling codecs from unpkg is that users can't self-host codecs and that working offline in node-js wouldn't work (to my understanding).

**Comment by manzt** [comment]
One idea I've been playing with is the ability to add a custom registry:

### zarr.js
```javascript
///////// 
// src/registry.ts
/////////
export const registry = new Map();

export function addCodec(id, fn) {
    registry.add(id, fn); // fn is an async function that imports a Codec interface
}

///////// 
// src/core.ts
/////////
import { registry } from './registry';

class ZarrArray {
  async function get(selection): {
      // pseudo code
      if (!self.compressor) {
          const codecId = self.meta.compressor.id;
          if (!(codecId in registry)) {
            throw Error("Codec not found in registry");
          }
          const importCodec = registry.get(codecId);
          const self.compressor = await importCodec();
      }
      ///
  }
}
```

### Client application
```javascript
// user application
import { addCodec, openArray } from 'zarr';

z = await openArray({ store: 'http://localhost:8000' });
z.get(null);
// This would error because there are no codecs in registry.

// add codecs
addCodec('blosc', () => import('numcodecs/blosc'));
addCodec('gzip', () => import('numcodecs/gzip'));
addCodec('zlib', () => import('numcodecs/zlib'));

z.get(null);
// codec is not in registry
```

This allows the application code to decide how modules are loaded, letting bundlers do code splitting for example.

**Comment by kylebarron** [comment]
> The issue with pulling codecs from unpkg is that users can't self-host codecs and that working offline in node-js wouldn't work (to my understanding).

For us, unpkg is just the default. [You can set to any other url of your choosing, or provide a local file](https://loaders.gl/docs/developer-guide/dependencies). All of our "loaders" work on Node and in the browser; I haven't dug into all the details of how the dynamic loading happens; maybe on Node it just loads the local file...

> Currently my thinking is that we don't have enough codecs to warrant a sophisticated dynamic registry

Yeah I agree; I think the scaffolding is a decent amount of work, so it's not a bad idea to wait until you know you need it.

As an aside, I'm probably putting my own exploration of visualizing Zarr datasets in deck.gl on the back burner, since I discovered that often the size of a single chunk is quite large. E.g. the open [Sea-Surface Temperature](https://registry.opendata.aws/mur/) dataset has blocks up to 100MB, which is too big for an interactive map. At least for direct-to-browser visualization, it seems you're kinda stuck with whatever the dataset creators' chose as the chunk size.
